[package]
org = "ballerinax"
name = "tool_consolidate_packages"
version = "@toml.version@"
distribution = "2201.12.0"
authors = ["Ballerina"]
keywords = ["consolidate-package", "consolidate", "consolidator"]
repository = "https://github.com/ballerina-platform/consolidate-packages-tool"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
